config/routes.rb
Rails.application.routes.draw do
  root "customers#index"

  resources :"customers" do
    resources :"orders"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
    belongs_to :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end
  def show
    @customer = Customer.find(params[:id])
  end
  def new
    @customer = Customer.new
  end

  def create 
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer
    else 
      render :new
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    redirect_to root_path
  end

  private
    def customer_params
      params.require(:customer).permit(:Name, :Phone, :Email, :Address)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    def create
        @customer = Customer.find(params[:customer_id])
        @order = @customer.orders.create(order_params)
        redirect_to customer_path(@customer)
      end
    
      private
        def order_params
          params.require(:order).permit(:OrderNumber, :OrderStatus,
        :BillingAddress, :ShippingAddress)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/_form.html.erb
<%= form_with model: customer do |form| %>

<div>
  <%= form.label :Name %>
  <%= form.text_field :Name %>
  <% @customer.errors.full_messages_for(:Name).each do |message| %>
      <div><%= message %></div>
    <% end %>
</div>

<div>
  <%= form.label :Phone %>
  <%= form.text_field :Phone %>
  <% @customer.errors.full_messages_for(:Phone).each do |message| %>
      <div><%= message %></div>
    <% end %>
</div>

<div>
  <%= form.label :Email %>
  <%= form.text_field :Email %>
  <% @customer.errors.full_messages_for(:Email).each do |message| %>
      <div><%= message %></div>
    <% end %>
</div>

<div>
  <%= form.label :Address %>
  <%= form.text_field :Address %>
  <% @customer.errors.full_messages_for(:Address).each do |message| %>
      <div><%= message %></div>
    <% end %>
</div>

<div>
  <%= form.submit %>
</div>

<% end %>

app/views/customers/edit.html.erb
<h1>Editing <%= @customer.Name %></h1>

<%= render "form", customer: @customer %>

app/views/customers/index.html.erb
<h1>Customers</h1>

<ul>
  <% @customers.each do |customer| %>
    <li>
      <%= link_to customer.Name, customer %>
    </li>
  <% end %>
  <div>
  <%= link_to "Add Customer", new_customer_url %>
  </div>
</ul>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render "form", customer: @customer %>

app/views/customers/show.html.erb
<h1><%= @customer.Name %></h1>

<p>Phone: <%= @customer.Phone %></p>
<p>Email: <%= @customer.Email %></p>
<p>Address: <%= @customer.Address %></p>
<p>Order:</p> 
<% @customer.orders.each do |order| %>
<p>
  <strong>Order Number:</strong>
    
      <%= order.OrderNumber %>
<% end %>
</P>


<ul>
  <li><%= link_to "Edit", edit_customer_path(@customer) %></li>
  <li><%= link_to "Destroy", customer_path(@customer),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>

<h2>Add a order:</h2>
<%= form_with model: [ @customer, @customer.orders.build ] do |form| %>
  <p>
    <%= form.label :OrderNumber %><br>
    <%= form.text_field :OrderNumber %>
  </p>

  <p>
    <%= form.label :OrderStatus %><br>
    <%= form.text_field :OrderStatus %>
  </p>

  <p>
    <%= form.label :BillingAddress %><br>
    <%= form.text_field :BillingAddress %>
  </p>

   <p>
    <%= form.label :ShippingAddress %><br>
    <%= form.text_field :ShippingAddress %>
  </p>

    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssignV3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>